replicaCount: 3

image:
  repository: ghcr.io/payment-platform/payment-gateway
  pullPolicy: IfNotPresent
  tag: "2.0.0-government-grade"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

env:
  FIPS_MODE: "true"
  PQ_CRYPTO_ENABLED: "true"
  RUST_LOG: "info"
  SERVER_PORT: "8080"

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
