apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: government-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/your-org/government-platform
    targetRevision: HEAD
    path: infra/k8s/charts
    helm:
      values: |
        global:
          fipsMode: true
          postQuantumCrypto: true
          securityLevel: "nist-level-5"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: gov-platform
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
