[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.15",
    "cryptography>=46.0.1",
    "prometheus-client>=0.23.1",
    "pydantic>=2.11.9",
    "redis>=6.4.0",
    "uvloop>=0.21.0",
]
